### ISSUE TITLE
What is the purpose of Harp in this project?

### ISSUE THREAD

**Issue by NataliaLKB** [CodersInDev/CloudListly#10]
What is it doing for you?

Could you easily do without it?

**Comment by NataliaLKB** [comment]
Especially because you use the python server in the README

**Comment by SimonLab** [comment]
We don't use harp anymore and we need indeed to delete the folder

**Comment by NataliaLKB** [comment]
@SimonLab perfect! Once that happens your project will look quite a bit more readable.

**Comment by NataliaLKB** [comment]
@SimonLab thanks for deleting!
